### ISSUE TITLE
npm run clean fails

### ISSUE THREAD

**Issue by danathurston** [LyndaExerciseFiles/angular2-essential-training#11]
What am I doing wrong? 

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@1.3.24
3 info using node@v0.10.25
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart angular2-essential-training@1.0.0
6 verbose unsafe-perm in lifecycle true
7 info angular2-essential-training@1.0.0 Failed to exec prestart script
8 error angular2-essential-training@1.0.0 prestart: `npm run clean`
8 error Exit status 1
9 error Failed at the angular2-essential-training@1.0.0 prestart script.
9 error This is most likely a problem with the angular2-essential-training package,
9 error not with npm itself.
9 error Tell the author that this fails on your system:
9 error     npm run clean
9 error You can get their info via:
9 error     npm owner ls angular2-essential-training
9 error There is likely additional logging output above.
10 error System Darwin 15.6.0
11 error command "node" "/usr/local/bin/npm" "start"
12 error cwd /Users/allstonians02134/angular2-essential-training
13 error node -v v0.10.25
14 error npm -v 1.3.24
15 error code ELIFECYCLE
16 verbose exit [ 1, true ]

**Comment by danathurston** [comment]
Does the local git repository have to be in my MAMP folder?

**Comment by danathurston** [comment]
![screen shot 2016-11-17 at 12 26 00 pm](https://cloud.githubusercontent.com/assets/3492404/20400581/4c63e2b0-acc3-11e6-982f-fb196c6688eb.png)

**Comment by konstantp** [comment]
@danathurston have you solved `npm start` issue?

**Comment by Bioninja01** [comment]
@konstantp I am having the same issue. Did you find a solution to the problem

**Comment by danathurston** [comment]
I picked up a contract and kind of let it fall by the wayside. Will work on
it this weekend. It shouldn't be too tough!

**Comment by Bioninja01** [comment]
I found a solution. In the tsconfig.json file change 
"target": "es5", -> "target": "es6",
This got it to work for me.

**Comment by konstantp** [comment]
Thanks @Bioninja01! It works!

**Comment by palavi** [comment]
It worked for me too. Thanks @Bioninja01

**Comment by GlenQu** [comment]
Tried changing the target but still no joy for me.  Upgraded Node and NPM.  Any other solutions?

> `0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Users\\gquinn\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'start' ]
> 2 info using npm@4.5.0
> 3 info using node@v6.10.3
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle angular2-essential-training@1.0.0~prestart: angular2-essential-training@1.0.0
> 6 verbose lifecycle angular2-essential-training@1.0.0~prestart: unsafe-perm in lifecycle true
> 7 verbose lifecycle angular2-essential-training@1.0.0~prestart: PATH: C:\Users\gquinn\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\gquinn\WebstormProjects\angular2-essential-training\node_modules\.bin;C:\oraclexe\app\oracle\product\11.2.0\server\bin;;C:\Program Files\Java\jdk1.8.0_101\bin;C:\dev\tools\apache-maven-3.3.9\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\CapgeminiScripts\Support Tools\;C:\Program Files (x86)\Common Files\Lenovo;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP\;C:\Users\gquinn\AppData\Local\GitHub\PortableGit_624c8416ee51e205b3f892d1d904e06e6f3c57c8\cmd\git.exe;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Cloud Foundry;C:\Program Files\MongoDB\Server\3.4\bin;C:\Program Files\nodejs\;C:\Program Files\Java\jre1.8.0_101\bin;C:\Users\gquinn\AppData\Roaming\Composer\vendor\bin;C:\xammp\php\;C:\Users\gquinn\AppData\Roaming\npm
> 8 verbose lifecycle angular2-essential-training@1.0.0~prestart: CWD: C:\Users\gquinn\WebstormProjects\angular2-essential-training
> 9 silly lifecycle angular2-essential-training@1.0.0~prestart: Args: [ '/d /s /c', 'npm run clean' ]
> 10 silly lifecycle angular2-essential-training@1.0.0~prestart: Returned: code: 7  signal: null
> 11 info lifecycle angular2-essential-training@1.0.0~prestart: Failed to exec prestart script
> 12 verbose stack Error: angular2-essential-training@1.0.0 prestart: `npm run clean`
> 12 verbose stack Exit status 7
> 12 verbose stack     at EventEmitter.<anonymous> (C:\Users\gquinn\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
> 12 verbose stack     at emitTwo (events.js:106:13)
> 12 verbose stack     at EventEmitter.emit (events.js:191:7)
> 12 verbose stack     at ChildProcess.<anonymous> (C:\Users\gquinn\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
> 12 verbose stack     at emitTwo (events.js:106:13)
> 12 verbose stack     at ChildProcess.emit (events.js:191:7)
> 12 verbose stack     at maybeClose (internal/child_process.js:886:16)
> 12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 13 verbose pkgid angular2-essential-training@1.0.0
> 14 verbose cwd C:\Users\gquinn\WebstormProjects\angular2-essential-training
> 15 verbose Windows_NT 6.1.7601
> 16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gquinn\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
> 17 verbose node v6.10.3
> 18 verbose npm  v4.5.0
> 19 error code ELIFECYCLE
> 20 error errno 7
> 21 error angular2-essential-training@1.0.0 prestart: `npm run clean`
> 21 error Exit status 7
> 22 error Failed at the angular2-essential-training@1.0.0 prestart script 'npm run clean'.
> 22 error Make sure you have the latest version of node.js and npm installed.
> 22 error If you do, this is most likely a problem with the angular2-essential-training package,
> 22 error not with npm itself.
> 22 error Tell the author that this fails on your system:
> 22 error     npm run clean
> 22 error You can get information on how to open an issue for this project with:
> 22 error     npm bugs angular2-essential-training
> 22 error Or if that isn't available, you can get their info via:
> 22 error     npm owner ls angular2-essential-training
> 22 error There is likely additional logging output above.
> 23 verbose exit [ 7, true ]`

Would appreciated any advice to go forward.

**Comment by jschwarty** [comment]
@GlenQu Can you post your `package.json` file so I can take a look at it?

**Comment by GlenQu** [comment]
Sure.

```
{
  "name": "angular2-essential-training",
  "version": "1.0.0",
  "author": "Justin Schwartzenberger",
  "description": "This project is the repository for my Angular 2 Essential Training course on Lynda.com.",
  "repository": {
    "type": "git",
    "url": "https://github.com/LyndaExerciseFiles/angular2-essential-training.git"
  },
  "scripts": {
    "clean": "rimraf app/**/*.js app/**/*.js.map",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "lite": "lite-server",
    "prestart": "npm run clean",
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" "
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "systemjs": "0.19.27",
    "core-js": "2.4.1",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.23"
  },
  "devDependencies": {
    "@types/core-js": "^0.9.34",
    "@types/node": "^6.0.41",
    "concurrently": "2.2.0",
    "lite-server": "2.2.2",
    "rimraf": "2.5.4",
    "typescript": "2.0.2"
  }
}

```

**Comment by jschwarty** [comment]
@GlenQu Can you try the following and let me know if that fixes it:

1. Update the `@types` in the `devDependencies` to not have carets:
```json
"@types/core-js": "0.9.34",
"@types/node": "6.0.41",
```
2. Delete the `node_modules` directory
3. Run `npm cache clean`
4. Run `npm install`

**Comment by GlenQu** [comment]
Hi Justin,

Followed the steps you outlined above but still no joy.  I am getting the same error.  I appreciate your help on this.

**Comment by GlenQu** [comment]
Got it working.  Now I tried multiple things to get it working.  I think ultimately I had to reinstall brackets (which I had uninstalled) then reconfigure the npmrc file.

On the npmrc file I changed my editor variable to use forward slashes instead of backslashes.  Restarted cmd and "npm start" worked.
